load("@aspect_bazel_lib//lib:tar.bzl", "tar")
load("@rules_distroless//distroless:defs.bzl", "group", "passwd")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_image_index", "oci_push")
load("//:transition.bzl", "multi_arch")

passwd(
    name = "passwd",
    entries = [{
        "uid": 100,
        "gid": 65534,
        "home": "/var/www",
        "shell": "/usr/sbin/nologin",
        "username": "www-data",
    }],
)

group(
    name = "group",
    entries = [{
        "name": "www-data",
        "gid": 65534,
    }],
)

tar(
    name = "sh",
    mtree = [
        "./bin/php type=link link=/usr/bin/php8.2",
        "./var/log/php8.2-fpm.log type=link link=/dev/stderr",
        "./run/php/php8.2-fpm.sock type=file",
    ],
)

oci_image(
    name = "image",
    architecture = select({
        "@platforms//cpu:arm64": "arm64",
        "@platforms//cpu:x86_64": "amd64",
    }),
    cmd = ["-F"],
    entrypoint = ["/usr/sbin/php-fpm8.2"],
    os = "linux",
    tags = ["manual"],
    tars = [
        ":sh",
        ":passwd",
        ":group",
        "@php-fpm-bookworm//:flat",
    ],
)

multi_arch(
    name = "images",
    image = ":image",
    platforms = [
        "//:linux-arm64",
        "//:linux-amd64",
    ],
)

oci_image_index(
    name = "index",
    images = [":images"],
)

oci_push(
    name = "push",
    image = ":index",
    remote_tags = ["8.2"],
    repository = "php-fpm",
)
