"distroless-php"

module(name = "distroless-php")

bazel_dep(name = "rules_oci", version = "2.2.6")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "toolchains_llvm", version = "1.4.0")
bazel_dep(name = "rules_distroless", version = "0.5.3")
bazel_dep(name = "aspect_bazel_lib", version = "2.21.1")
bazel_dep(name = "chrome-linux-sysroot", version = "0.0.3")

# git_override(
#     module_name = "rules_distroless",
#     commit = "f994712f6bd573b3d50b207ae5fa3df077caed67",
#     remote = "https://github.com/GoogleContainerTools/rules_distroless.git",
# )

PHP_VERSIONS = [
    "7.2",
    "7.4",
    "8.3",
    "8.4",
]

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "ca-certificates",
    build_file_content = 'exports_files(["data.tar.xz", "control.tar.xz"])',
    sha256 = "ef590f89563aa4b46c8260d49d1cea0fc1b181d19e8df3782694706adf05c184",
    urls = ["https://snapshot.debian.org/archive/debian/20250827T085636Z/pool/main/c/ca-certificates/ca-certificates_20250419_all.deb"],
)

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    name = "llvm_toolchain",
    llvm_version = "16.0.0",
)
llvm.sysroot(
    name = "llvm_toolchain",
    label = "@chrome-linux-sysroot//:debian_bullseye_arm64",
    targets = ["linux-aarch64"],
)
use_repo(llvm, "llvm_toolchain")

apt = use_extension(
    "@rules_distroless//apt:extensions.bzl",
    "apt",
)

apt.install(
    name = "php-common",
    lock = "//php:common.lock.json",
    manifest = "//php:common.yaml",
)

apt.install(
    name = "php-wkhtmltopdf",
    lock = "//php:wkhtmltopdf.lock.json",
    manifest = "//php:wkhtmltopdf.yaml",
)

[apt.install(
    name = "php-{}".format(version),
    lock = "//php/{}:php.lock.json".format(version),
    manifest = "//php/{}:php.yaml".format(version),
) for version in PHP_VERSIONS]

apt.install(
    name = "nginx-bookworm",
    lock = "//nginx:bookworm.lock.json",
    manifest = "//nginx:bookworm.yaml",
    resolve_transitive = False,
)

use_repo(apt, "nginx-bookworm", "php-common", "php-wkhtmltopdf", "php-7.2", "php-7.4", "php-8.3", "php-8.4")
