user www-data;
worker_processes auto;

http {
    tcp_nodelay on;
    client_body_buffer_size 16k;
    client_header_buffer_size 1k;
    large_client_header_buffers 4 8k;

    server {
        listen       80;
        server_name  localhost;
        root         /var/www/html;
        include      /etc/nginx/mime.conf;
        include      /etc/nginx/conf.d/*.conf;

        access_log /dev/stdout;
        error_log  /dev/stderr;
        index index.html index.htm index.php;

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/run/php/php-fpm.sock;
            fastcgi_index index.php;
            fastcgi_read_timeout 300;
            proxy_read_timeout 300;
            include fastcgi.conf;
        }
    }
}

events {}
